import Head from "next/head";
import styles from '@styles/home.module.css'
import { Card } from "../components/Card/Card";
import { Banner } from "@components/Banner/Banner";
import { Carousel } from "@components/Carousel/Carousel";
import { Projects } from "@constants/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portifolio Julia Benedicto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <Banner />
      
      <div className={styles.containerTitle}>
        <h2 className={styles.title}>Projetos</h2>
      </div>
      <Carousel>
        {Projects.map(({image, title, description, link, github}) => (
        <Card key={title} image={image} title={title} text={description} github={github} link={link}/>
        ))}
        </Carousel>
      </main>
    </>
  );
}
